### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by ramazan5134** [matteocelani/BinanceNFT#1]
hi you have telegram ı want to speak you

**Comment by matteocelani** [comment]
Write me on twitter, find my account on my profile.

**Comment by ramazan5134** [comment]
hi again ı cant you find dm button

**Comment by matteocelani** [comment]
@mashuEth

on twitter

**Comment by ramazan5134** [comment]
I followed you but no message sending

**Comment by ramazan5134** [comment]
if possible can you write to me @RamazanDogru15
